<?php

declare(strict_types=1);

namespace GeoJsonProxy;

/**
 * Global constants for the GeoJSON proxy
 */

// Load from config file
require_once __DIR__ . '/../../config/config.php';

// Re-export all constants in the GeoJsonProxy namespace
const VERSION = \VERSION;
const EMPTY_FEATURE_COLLECTION_JSON = \EMPTY_FEATURE_COLLECTION_JSON;
const SOURCE_URL = \SOURCE_URL;
const BUFFER_URL = \BUFFER_URL;
const TRANSPORT_MODE_PROPERTY = \TRANSPORT_MODE_PROPERTY;
const ALLOWED_TRANSPORT_MODE_TYPES = \ALLOWED_TRANSPORT_MODE_TYPES;
const CACHE_DIR = \CACHE_DIR;
const CACHE_TTL = \CACHE_TTL;
const STALE_TTL = \STALE_TTL;
const MAX_BYTES = \MAX_BYTES;
const HTTP_TIMEOUT = \HTTP_TIMEOUT;
const USER_AGENT = \USER_AGENT;
const GEO_EPSILON = \GEO_EPSILON;
const DEBUG_LOG_ENABLED = \DEBUG_LOG_ENABLED;
const DEBUG_LOG_FILENAME = \DEBUG_LOG_FILENAME;
const STATUS_FILENAME = \STATUS_FILENAME;
const STATUS_ENDPOINT_ENABLED = \STATUS_ENDPOINT_ENABLED;
const LOG_PROGRESS_EVERY = \LOG_PROGRESS_EVERY;
const PACKED_SEGMENT_BYTES = \PACKED_SEGMENT_BYTES;
const PACKED_ID_BYTES = \PACKED_ID_BYTES;
const SPATIAL_INDEX_TARGET_SEGMENTS_PER_CELL = \SPATIAL_INDEX_TARGET_SEGMENTS_PER_CELL;
const SPATIAL_INDEX_MAX_TOTAL_CELLS = \SPATIAL_INDEX_MAX_TOTAL_CELLS;
const SPATIAL_INDEX_MAX_GRID_DIMENSION = \SPATIAL_INDEX_MAX_GRID_DIMENSION;
const SPATIAL_INDEX_MAX_CELLS_PER_SEGMENT = \SPATIAL_INDEX_MAX_CELLS_PER_SEGMENT;
const SPATIAL_INDEX_MAX_REFERENCE_BYTES = \SPATIAL_INDEX_MAX_REFERENCE_BYTES;
const POINT_INDEX_TARGET_EDGES_PER_BUCKET = \POINT_INDEX_TARGET_EDGES_PER_BUCKET;
const POINT_INDEX_MAX_BUCKETS = \POINT_INDEX_MAX_BUCKETS;
const POINT_INDEX_MAX_BUCKETS_PER_EDGE = \POINT_INDEX_MAX_BUCKETS_PER_EDGE;
const POINT_INDEX_MAX_REFERENCE_BYTES = \POINT_INDEX_MAX_REFERENCE_BYTES;
const COMPACT_SEGMENT_MAX_BYTES = \COMPACT_SEGMENT_MAX_BYTES;
const MEMORY_SAFETY_RESERVE_BYTES = \MEMORY_SAFETY_RESERVE_BYTES;
